In [2]:
import numpy as np
from time import time

In [32]:
np.array([1,2,3,4,5])
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [33]:
a = np.random.rand(100) # Create N length 1D array (here N=100)
print(a.shape)
print(len(a))

(100,)
100


In [34]:
a = np.random.rand(12,4)
print(a.shape)

(12, 4)


In [37]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic=time()
c = np.dot(a,b)
print("Vectorized Time:     {} ms".format((time()-tic)*1000))

c=0
tic=time()
for i in range(len(a)):
    c += a[i]*b[i]
print("Non-Vectorized Time: {} ms".format((time()-tic)*1000))

Vectorized Time:     2.000570297241211 ms
Non-Vectorized Time: 1739.3922805786133 ms


In [1]:
import math
x = np.array([1, 2, 3])
1/(1+np.exp(-x))

NameError: name 'np' is not defined

In [5]:
a = np.random.rand(32,32,3)
print(a.shape)

(32, 32, 3)


In [8]:

print(a.reshape(32*32*3,1).shape)

(3072, 1)


In [17]:
a = np.random.randn(2, 3)
b = np.random.randn(2, 1)
(a+b).shape

(2, 3)

In [19]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c.shape

(12288, 45)

In [32]:
a = np.random.randn(3, 4)
b = np.random.randn(4, 1)
c = np.random.randn(3, 4)

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]
print(c)

[[-0.70877346 -1.39360373  1.27392164 -1.75329819]
 [-0.00945066 -0.99061619 -0.71563974 -3.03061572]
 [ 0.19311103 -0.24893207 -0.66441026 -2.26319836]]


In [34]:
c= a+b.T
c

array([[-0.70877346, -1.39360373,  1.27392164, -1.75329819],
       [-0.00945066, -0.99061619, -0.71563974, -3.03061572],
       [ 0.19311103, -0.24893207, -0.66441026, -2.26319836]])

In [36]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[-0.04870404,  0.01601815,  0.09039888],
       [-0.31086561,  1.44908876, -0.29576735],
       [ 0.05064982,  0.04035628, -0.52789086]])